# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver import Chrome

class TestLogin():
  def setup_method(self, method):
    self.driver = Chrome(executable_path='/home/nandish/Documents/RTO/chromedriver')
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_login(self):
    # Test name: login
    # Step # | name | target | value | comment
    # 1 | open | / |  | 
    self.driver.get("http://localhost:5000/")
    # 2 | setWindowSize | 1050x711 |  | 
    self.driver.set_window_size(1050, 711)

    # 3 | click | css=.fa-user-circle |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".fa-user-circle").click()
    # 4 | click | id=email |  | 
    self.driver.find_element(By.ID, "email").click()
    # 5 | type | id=email | nandishbj23@gmail.com | 
    self.driver.find_element(By.ID, "email").send_keys("nandishbj23@gmail.com")
    # 6 | click | id=password |  | 
    self.driver.find_element(By.ID, "password").click()
    # 7 | type | id=password | 1234 | 
    self.driver.find_element(By.ID, "password").send_keys("1234")
    # 8 | click | name=login |  | 
    self.driver.find_element(By.NAME, "login").click()
  
