# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary
from selenium.webdriver import Firefox


class TestLogin():
  def setup_method(self, method):
    
    self.driver = webdriver.Firefox(executable_path='/home/nandish/Documents/RTO/testcases/geckodriver')
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_login(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1264, 692)
    self.driver.find_element(By.CSS_SELECTOR, ".dropbtn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fa-user-circle").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("nan")
    self.driver.find_element(By.ID, "email").send_keys(Keys.DOWN)
    self.driver.find_element(By.ID, "email").send_keys("nandishbj23@gmail.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("1234")
    self.driver.find_element(By.NAME, "login").click()
    
  
